name: main

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  SRC_DIR: optyx
  TEST_DIR: test
  DOCS_DIR: docs

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install linter
      run:
        python -m pip install pyproject-flake8 coverage pylint
    - name: Check for errors
      run:
        # stop the build if there are Python syntax errors or undefined names
        pflake8 ${{ env.SRC_DIR }}
    - name: pylint
      run:
        pylint ${{ env.SRC_DIR }}
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # caching pip dependencies
    - name: Install
      run: |
        pip install coverage pytest
        pip install .[test]
    - name: Test
      run:
        coverage run -m pytest
    - name: Coverage
      run:
        coverage report --fail-under=99 --show-missing
